//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace itcast.crm16.Services
{
    using System;
    using System.Collections.Generic;

    using itcast.crm16.IServices;
    using itcast.crm16.model;
    using itcast.crm16.IRepository;
    using Site.Models;
    using System.Linq;

    public partial class CommerceServices : BaseBLL<Commerce>, ICommerce
    {
        ICommerceRepository dal;
        public CommerceServices(ICommerceRepository dal)
        {
            this.dal = dal;
            base.basedal = dal;
        }

        public IEnumerable<CommerceViewModel> GetItemModel(int index, string name, out int totalPage, int type, int pageSize = 10)
        {
            List<Commerce> itemList = null;
            if (string.IsNullOrWhiteSpace(name))
            {
                itemList = dal.QueryByPage(index, pageSize, out totalPage, c => c.IsDelete == 0 && c.Type == type, c => c.id).ToList<Commerce>();
            }
            else
            {
                itemList = dal.QueryByPage(index, pageSize, out totalPage, c => c.IsDelete == 0 && c.Type == type && c.Name.Contains(name), c => c.id).ToList<Commerce>();
            }
            int newid = 1;
            if (index > 1)
            {
                newid = (index - 1) * 10 + newid;
            }
            return itemList.Select(d => new CommerceViewModel
            {
                Nid = newid++,
                IsDelete = d.IsDelete,
                LookBool = d.Look == 0 ? true : false,
                id = d.id,
                Contents = d.Contents.Length > 10 ? d.Contents.Substring(0, 8) : d.Contents,
                Creater = d.Creater,
                CreateTime = d.CreateTime,
                Look = d.Look,
                Name = d.Name,
                Remark = d.Remark,
                ImageUrl=d.ImageUrl,
                UpdateTime = d.UpdateTime,
                UpdateTimeStr = d.UpdateTime.ToShortDateString(),
                typeName = d.Type
            });
        }
    }
}

