//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace itcast.crm16.Services
{
    using System;
    using System.Collections.Generic;

    using itcast.crm16.IServices;
    using itcast.crm16.model;
    using itcast.crm16.IRepository;
    using Site.Models;
    using System.Linq;
    using System.Linq.Expressions;
    using System.Web.WebPages;

    public partial class CommerceServices : BaseBLL<Commerce>, ICommerce
    {
        ICommerceRepository dal;
        public CommerceServices(ICommerceRepository dal)
        {
            this.dal = dal;
            base.basedal = dal;
        }
        /// <summary>
        /// 
        /// </summary>
        /// <param name="index"></param>
        /// <param name="name"></param>
        /// <param name="totalPage"></param>
        /// <param name="type"></param>
        /// <param name="pageSize"></param>
        /// <param name="IsShow">是否显示在网站前台</param>
        /// <returns></returns>
        public IEnumerable<CommerceViewModel> GetItemModel(int index, string name, out int totalPage, int type, int pageSize = 10, bool IsShow=false)
        {
            List<Commerce> itemList = null;
            Expression<Func<Commerce, bool>> where;
            Expression<Func<Commerce, int>> sort = c => c.id; 
            if (string.IsNullOrWhiteSpace(name))
            {
                where = (c => c.IsDelete == 0 && c.Type == type);
                if (IsShow)
                {
                    where = (c => c.IsDelete == 0 && c.Type == type&&c.Look==0);
                    sort = c => (int)c.Sort;
                }
            }
            else
            {
                where = (c => c.IsDelete == 0 && c.Type == type && c.Name.Contains(name));
                if (IsShow)
                {
                    where = (c => c.IsDelete == 0 && c.Type == type && c.Look == 0 && c.Name.Contains(name));
                    sort = c => (int)c.Sort;
                }
            }
            if (IsShow)
            {
                itemList = dal.QueryByPageASC(index, pageSize, out totalPage, where, sort).ToList<Commerce>();
            }
            else
            {
                itemList = dal.QueryByPage(index, pageSize, out totalPage, where, sort).ToList<Commerce>();
            }
           
            int newid = 1;
            if (index > 1)
            {
                newid = (index - 1) * 10 + newid;
            }
           
            var list= itemList.Select(d => new CommerceViewModel
            {
                Nid = newid++,
                IsDelete = d.IsDelete,
                LookBool = d.Look == 0 ? true : false,
                id = d.id,
                Contents = d.Contents.Length > 10&&IsShow==false ? d.Contents.Substring(0, 8) : d.Contents,
                Creater = d.Creater,
                CreateTime = d.CreateTime,
                Look = d.Look,
                Name = d.Name,
                Remark = d.Remark,
                ImageUrl=d.ImageUrl,
                UpdateTime = d.UpdateTime,
                UpdateTimeStr = d.UpdateTime.ToShortDateString(),
                typeName = d.Type,
                Sort=string.IsNullOrWhiteSpace(d.Sort.ToString())?0:(int)d.Sort,
                NSort=d.Remark.IsInt()? d.Remark.AsInt():10000,
            });
            if (!IsShow)
            {
                return list;
            }
            List<CommerceViewModel> newlist = new List<CommerceViewModel>();
            foreach (var List in list.GroupBy(c=>c.Sort))
            {
                foreach (var item in List.OrderBy(p => p.NSort))
                {
                    newlist.Add(item);
                }
            }
            return newlist;
        }
    }
}

