//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace itcast.crm16.IServices
{
    using System;
    using System.Collections.Generic;
    
    using itcast.crm16.model;
    public partial interface IManageServices:IBaseBLL<Manage>
    {
        /// <summary>
        /// 前端分页获取显示企业管理数据
        /// </summary>
        /// <param name="pageIndex"></param>
        /// <param name="pageSize"></param>
        /// <param name="count"></param>
        /// <returns></returns>
        List<Manage> GetManageByPage(int pageIndex, int pageSize, out int count);

        /// <summary>
        /// 获取指定id的企业管理详细数据
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        Manage GetManageById(int id);


        /// <summary>
        /// 企业点赞
        /// </summary>
        /// <param name="id"></param>
        /// <param name="praise"></param>
        /// <returns></returns>
        bool ManagePraise(int id, int praise);


    }
}
