//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace itcast.crm16.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteSet
    {
        public int id { get; set; }
        public string Title { get; set; }
        public string Image { get; set; }
        public string Contents { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> CreatTime { get; set; }
        public string Remark { get; set; }
        public int type { get; set; }
        public Nullable<int> Look { get; set; }
    }
}
